# Generated by Django 5.1.1 on 2024-09-22 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCustomerLoanData',
            fields=[
                ('unique_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('reporting_date', models.DateField()),
                ('account_number', models.CharField(max_length=40)),
                ('loan_type', models.CharField(max_length=25)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('days_past_due', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Add a description to your project', max_length=255)),
                ('report_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='impairment.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLoanDataLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_frozen', models.BooleanField(default=False)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('loan_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impairment.historicalcustomerloandata')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_data', to='impairment.project')),
            ],
        ),
    ]
