# Generated by Django 5.1.1 on 2024-09-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Add a description to your project', max_length=100),
        ),
    ]
