# Generated by Django 5.1.1 on 2024-09-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairment', '0002_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Locked', 'Locked')], default='Active', max_length=10),
        ),
    ]
