# Generated by Django 5.1.1 on 2024-09-26 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairment', '0004_alter_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalcustomerloandata',
            old_name='account_number',
            new_name='account_no',
        ),
        migrations.RenameField(
            model_name='historicalcustomerloandata',
            old_name='outstanding_balance',
            new_name='out_balance',
        ),
        migrations.RemoveField(
            model_name='calculationresult',
            name='data',
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='base_transition_matrix',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='ead_results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='ecl_results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='lgd_inputs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='lgd_results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='stage_1_cumulative',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='stage_1_marginal',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='stage_2_cumulative',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='stage_2_marginal',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomerloandata',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pd_data', to='impairment.project'),
            preserve_default=False,
        ),
    ]
