# Generated by Django 5.1.1 on 2024-10-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairment', '0004_alter_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='version',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
