# Generated by Django 5.1.1 on 2024-09-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impairment', '0005_rename_account_number_historicalcustomerloandata_account_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalcustomerloandata',
            old_name='reporting_date',
            new_name='date',
        ),
    ]
