# Generated by Django 5.1.1 on 2024-10-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairment', '0005_alter_project_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='eadlgdcalculationresult',
            name='loan_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
