# Generated by Django 5.1.1 on 2024-09-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairment', '0006_rename_reporting_date_historicalcustomerloandata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcustomerloandata',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='historicalcustomerloandata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='historicalcustomerloandata',
            name='days_past_due',
        ),
        migrations.RemoveField(
            model_name='historicalcustomerloandata',
            name='loan_type',
        ),
        migrations.RemoveField(
            model_name='historicalcustomerloandata',
            name='out_balance',
        ),
        migrations.RemoveField(
            model_name='historicalcustomerloandata',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='historicalcustomerloandata',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomerloandata',
            name='file_upload_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomerloandata',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcustomerloandata',
            name='uploaded_file',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
