# Generated by Django 5.1.1 on 2024-10-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairment', '0006_eadlgdcalculationresult_loan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eadlgdcalculationresult',
            name='effective_interest_rate',
            field=models.DecimalField(decimal_places=19, max_digits=20, null=True),
        ),
    ]
