# Generated by Django 5.1.1 on 2024-10-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairment', '0007_eadlgdcalculationresult_effective_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eadlgdcalculationresult',
            name='effective_interest_rate',
            field=models.FloatField(max_length=15, null=True),
        ),
    ]
