# Generated by Django 5.1.1 on 2024-09-26 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impairment', '0007_remove_historicalcustomerloandata_account_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectLoanDataLink',
        ),
    ]
