# Generated by Django 5.1.1 on 2024-10-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impairment', '0008_alter_eadlgdcalculationresult_effective_interest_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eclcalculationresult',
            name='ead_lgd_data',
        ),
        migrations.RemoveField(
            model_name='eclcalculationresult',
            name='pd_data',
        ),
    ]
