# Generated by Django 5.1.1 on 2024-09-27 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairment', '0008_delete_projectloandatalink'),
    ]

    operations = [
        migrations.CreateModel(
            name='EADLGDCalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lgd_inputs', models.JSONField(blank=True, null=True)),
                ('lgd_results', models.JSONField(blank=True, null=True)),
                ('ead_results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ead_lgd_calculations', to='impairment.project')),
            ],
        ),
        migrations.CreateModel(
            name='PDCalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_transition_matrix', models.JSONField(blank=True, null=True)),
                ('stage_1_cumulative', models.JSONField(blank=True, null=True)),
                ('stage_2_cumulative', models.JSONField(blank=True, null=True)),
                ('stage_1_marginal', models.JSONField(blank=True, null=True)),
                ('stage_2_marginal', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pd_calculations', to='impairment.project')),
            ],
        ),
        migrations.CreateModel(
            name='ECLCalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecl_results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ead_lgd_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impairment.eadlgdcalculationresult')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecl_calculations', to='impairment.project')),
                ('pd_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impairment.pdcalculationresult')),
            ],
        ),
        migrations.DeleteModel(
            name='CalculationResult',
        ),
    ]
