# Generated by Django 5.1.1 on 2024-09-27 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairment', '0009_eadlgdcalculationresult_pdcalculationresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcustomerloandata',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eadlgdcalculationresult',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ead_lgd_calculations', to='impairment.project'),
        ),
        migrations.AlterField(
            model_name='eclcalculationresult',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecl_calculations', to='impairment.project'),
        ),
        migrations.AlterField(
            model_name='pdcalculationresult',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pd_calculations', to='impairment.project'),
        ),
    ]
