# Generated by Django 5.1.1 on 2024-10-10 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairment', '0009_remove_eclcalculationresult_ead_lgd_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentloanbook',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_loan_data', to='impairment.project'),
        ),
    ]
