# Generated by Django 5.1.1 on 2024-10-10 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairment', '0010_alter_currentloanbook_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='version',
            field=models.CharField(max_length=35),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('company', 'report_date', 'version'), name='unique_version_per_company_and_date'),
        ),
    ]
