# Generated by Django 5.1.1 on 2024-09-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairment', '0010_historicalcustomerloandata_is_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdcalculationresult',
            name='cures',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdcalculationresult',
            name='recoveries',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
