# Generated by Django 5.1.1 on 2024-09-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairment', '0012_rename_ead_results_eadlgdcalculationresult_amortization_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eadlgdcalculationresult',
            name='stage',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
