# Generated by Django 5.1.1 on 2024-09-30 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairment', '0013_eadlgdcalculationresult_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentLoanBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.JSONField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_loan_data', to='impairment.project')),
            ],
        ),
    ]
